db_path: "data"
val_percent: 0.1

epochs: 50
warmup_epochs: 7
optim: "sgd"
weight_decay: 0.0005
lr: 0.001
momentum: 0.9
save_freq: 1
resume: false
ckpt: ""

loader_cfg:
  train:
    batch_size: 8
    shuffle: true
    num_workers: 4
    pin_memory: true
    persistent_workers: true
  val:
    batch_size: 8
    shuffle: false
    num_workers: 4
